services:
  mysql:
    image: mysql:8.3.0
    container_name: order_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeinprod
    volumes:
      - mysql_order_data:/vat/lib/mysql

volumes:
  mysql_order_data: